[package]
name = "leads"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.8", features = ["derive"] }
colored = "2.1.0"
indicatif = "0.17.8"
polars = { version = "0.41.3", features = ["parquet"] }
thiserror = "1.0.63"
